apiVersion: cache.my.domain/v1alpha1
kind: Memcached
metadata:
  labels:
    app.kubernetes.io/name: example-operator-sdk-go
    app.kubernetes.io/managed-by: kustomize
  name: memcached-sample
spec:
  # TODO(user): Add fields here
